version: '3.8'

services:
  webapp:
    container_name: webapp
    hostname: webapp
    build: 
      context: sweet-social-webapp
      dockerfile: Dockerfile
    environment:
      - VITE_BASE_URL=https://sweetdev.site/v1/api
      - VITE_GOOGLE_OAUTH_CLIENT_ID=<YOUR_GOOGLE_OAUTH_CLIENT_ID>
      - VITE_SOCKET_URL=https://sweetdev.site/socket
    ports:
      - '5173:5173'
    networks:
      - shared-network

  server:
    container_name: server
    hostname: server
    build:
      context: sweet-social-server
      dockerfile: Dockerfile
      
    environment:
      - POSTGRESQL_HOST=db
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=123456
      - POSTGRESQL_DB=sweet-social

      - JWT_SECRET=jwtsecret
      - CLIENT_URL=https://sweetdev.site

      - EMAIL_HOST=<YOUR_SENDGRID_EMAIL_HOST>
      - EMAIL_USER=<YOUR_SENDGRID_EMAIL_KEY>
      - EMAIL_PASSWORD=<YOUR_SENDGRID_EMAIL_PASS>

      - GCP_PROJECT_ID=<YOUR_GCP_PROJECT_ID>
      - GCP_BUCKET_NAME=<YOUR_GCP_BUCKET_NAME>

      - GOOGLE_CLIENT_ID=<YOUR_GOOGLE_OAUTH_CLIENT_ID>
      - GOOGLE_CLIENT_SECRET=<YOUR_GOOGLE_OAUTH_CLIENT_SECRET>
      
    ports:
      - '9000:9000'
    networks:
      - shared-network

  db:
    image: postgres:latest
    container_name: db
    hostname: db
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: sweet-social
    volumes:
      - db-data:/var/lib/postgresql/data

    ports:
      - '5432:5432'
    networks:
      - shared-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      
    depends_on:
      server:
        condition: service_started

    networks:
      - shared-network

volumes:
  db-data:

networks:
  shared-network:
    driver: bridge

  